parameters:
    gaz_analytics.tracking_information.class: Gaz\AnalyticsBundle\Helper\TrackingInformationHelper

services:
    gaz_analytics.tracking_information:
        class: %gaz_analytics.tracking_information.class%
        arguments:
            - @ezpublish.config.resolver
            - @ezpublish.api.service.location
            - @ezpublish.api.service.content
            - @ezpublish.api.service.user
            - @ezpublish.api.service.content_type
            - @service_container
            - @logger